// ignore: constant_identifier_names
enum Endpoint {
  LOGIN,
  VERIFY_OTP,
  REGISTER_LOGIN_TYPE,
  RESEND_OTP,
  GET_SESSION_INFO,
  CLEAR_USER_DEVICE,
  LOGOUT,
  GET_ACTIVATION_CODE_SMART_OTP,
  GET_ACCOUNT_LIST,
  RECEIVER_STATEMENT_ONLINE,
  RECEIVER_STATEMENT_OFFLINE,
  MADE_FUND_VERIFY,
  COMMIT_TRANSACTION,
  GET_EXCHANGE_RATE,
  GET_MENU_USER_PERMISSION,
  GET_SUPPORTED_CURRENCY,
  GET_TRANSACTION_LIST,
  GET_TRANSACTION_LIST_WAIT_APPROVE,
  GET_TRANSACTION_SAVING_LIST_WAIT_APPROVE,
  GET_TRANSACTION_FX_LIST_WAIT_APPROVE,
  GET_TRANSACTION_SERVICE_TYPE,
  GET_TRANSACTION_SAVING_SERVICE_TYPE,
  GET_TRANSACTION_FX_SERVICE_TYPE,
  GET_LIST_SAVING_ACCOUNT,
  GET_PAYROLL_LIST_WAIT_APPROVE,
  GET_LIST_DEBIT_SAVING_ACCOUNT,
  GET_AZ_DETAIL,
  CLOSE_AZ_INIT,
  CLOSE_AZ_CONFIRM,
  CLOSE_AZ_COMMIT,
  GET_TRANSACTION_DETAIL,
  GET_DEBIT_ACCOUNT_DETAIL,
  CHANGE_PASSWORD,

  // Transaction manage
  TRANSACTION_MANAGE_INIT,
  TRANSACTION_FX_MANAGE_INIT,
  TRANSACTION_FX_MANAGE_CONFIRM,
  TRANSACTION_FX_MANAGE_COMMIT,
  TRANSACTION_MANAGE_CONFIRM,
  TRANSACTION_SAVING_MANAGE_INIT,
  TRANSACTION_SAVING_MANAGE_CONFIRM,
  TRANSACTION_SAVING_MANAGE_COMMIT,
  TRANSACTION_PAYROLL_MANAGE_INIT,
  TRANSACTION_PAYROLL_MANAGE_CONFIRM,
  TRANSACTION_PAYROLL_MANAGE_COMMIT,
  TRANSACTION_PAYROLL_MANAGE_GET_BEN_LIST,
  GET_CITY_LIST,
  GET_BRANCH_LIST,
  RESEND_VERIFY_OTP,
  GET_BANNER_AD,
  GET_ROLLOVER_TERM_SAVING_ONLINE,

  //Transfer
  GET_LIST_DEBIT_ACCOUNT,
  GET_BEN_ACCOUNT_DETAIL,
  TRANSFER_INIT,
  TRANSFER_CONFIRM,
  GET_BEN_BANKS,
  GET_BEN_LIST,
  GET_TRANSFER_RATE,

  // Notification
  GET_LIST_ACCOUNT_SETTING_NOTIFICATION,
  GET_LIST_HISTORY_BALANCE_ALERT,
  GET_LIST_PAYMENT_PENDING_ALERT,
  POST_REGISTER_ACCOUNT_NOTIFICATIONS,
  POST_DEREREGISTER_ACCOUNT_NOTIFICATIONS,
  POST_HAS_READ_NOTIFICATIONS,
  GET_LIST_NOTIFICATION_PROMOTE,

  //Deposits
  GET_SAVING_DEPOSITS_PRODCUT,
  OPEN_SAVING_VERIFY,

  //CARD
  GET_CARD_LIST,
  GET_CARD_CONTRACT_LIST,
  GET_CARD_CONTRACT_INFO,
  GET_CARD_INFO,
  GET_CARD_HISTORY,
  GET_CARD_STATEMENT,
  GET_CARD_STATEMENT_MONTH,

  //LOAN
  GET_LOAN_LIST,
  GET_LOAN_DETAIL,
  GET_LOAN_STATEMENT,
  EXPORT_LOAN_DUE_DATE,

  //Tax
  GET_TAX_ONLINE,
  GET_TAX_ONLINE_LIST,
  MANAGE_TAX_ONLINE_INIT,
  MANAGE_TAX_ONLINE_CONFIRM,
  MANAGE_TAX_ONLINE_COMMIT,

  //LC, Nho thu, bao lanh
  GET_LC,
  GET_GAURANTEE,
  GET_NEGOTING,
  GET_LC_CONTRACT_LIST,

  //BIll
  GET_BILL_SERVICE,
  GET_BILL_PROVIDER,
  GET_BILL_INFO,
  GET_BILL_SAVED,
  BILL_INIT,
  BILL_CONFIRM,
  BILL_VERIFY,
  GET_BILL_WAITING_APPROVAL,
  GET_BILL_DEBIT_ACCOUNT,
  INIT_BILL_MANAGE,
  CONFIRM_BILL_MANAGE,
  COMMIT_BILL_MANAGE,
}

var _data = {
  Endpoint.LOGIN: '/Authentication/Login',
  Endpoint.VERIFY_OTP: '/Authentication/VerifyOTPLogin',
  Endpoint.REGISTER_LOGIN_TYPE: '/Authentication/RegisterLoginType',
  Endpoint.RESEND_OTP: '/Authentication/ResendOTPLogin',
  Endpoint.GET_SESSION_INFO: '/Authentication/GetSessionInfo',
  Endpoint.LOGOUT: '/Authentication/Logout',
  Endpoint.CLEAR_USER_DEVICE: '/Authentication/CleanUserDevice',
  Endpoint.GET_ACTIVATION_CODE_SMART_OTP:
      '/Authentication/GetActivationCodeSmartOTP',
  Endpoint.GET_ACCOUNT_LIST: '/Account/GetAcountList',
  Endpoint.RECEIVER_STATEMENT_ONLINE: '/Account/ReceiveStatementOnline',
  Endpoint.RECEIVER_STATEMENT_OFFLINE: '/Account/ReceiveStatementOffline',
  Endpoint.MADE_FUND_VERIFY: '/MadeFund/Verify',
  Endpoint.COMMIT_TRANSACTION: '/ManageTransaction/CommitTransaction',
  Endpoint.GET_EXCHANGE_RATE: '/Category/GetExchangeRate',
  Endpoint.GET_MENU_USER_PERMISSION: '/Authentication/GetMenuUserPermission',
  Endpoint.GET_SUPPORTED_CURRENCY: '/Category/GetCurrency',
  Endpoint.GET_TRANSACTION_LIST: '/Inquiry/GetTransactionHistoryList',
  Endpoint.GET_TRANSACTION_LIST_WAIT_APPROVE: '/ManageTransaction/GetListTransferWaitingForApproval',
  Endpoint.GET_TRANSACTION_SAVING_LIST_WAIT_APPROVE: '/SavingOnline/GetListTransferWaitingForApproval',
  Endpoint.GET_TRANSACTION_FX_LIST_WAIT_APPROVE: '/ManageFxTransaction/GetListTransferWaitingForApproval',
  Endpoint.GET_TRANSACTION_SERVICE_TYPE: '/ManageTransaction/GetListServiceType',
  Endpoint.GET_TRANSACTION_SAVING_SERVICE_TYPE: '/SavingOnline/GetListServiceType',
  Endpoint.GET_TRANSACTION_FX_SERVICE_TYPE: '/ManageFxTransaction/GetListServiceType',
  Endpoint.GET_LIST_SAVING_ACCOUNT: '/SavingOnline/GetListSavingAccount',
  Endpoint.GET_LIST_DEBIT_SAVING_ACCOUNT: '/SavingOnline/GetListDebitAccount',
  Endpoint.GET_PAYROLL_LIST_WAIT_APPROVE: '/Payroll/GetSalaryTransferList',
  Endpoint.GET_AZ_DETAIL: '/SavingOnline/GetAzByAcountNumber',
  Endpoint.CLOSE_AZ_INIT: '/SavingOnline/CloseAzInit',
  Endpoint.CLOSE_AZ_CONFIRM: '/SavingOnline/Confirm',
  Endpoint.CLOSE_AZ_COMMIT: '/SavingOnline/Verify',
  Endpoint.GET_TRANSACTION_DETAIL: '/Inquiry/GetTransactionHistoryDetail',
  Endpoint.GET_DEBIT_ACCOUNT_DETAIL: '/MadeFund/GetDebitAccountDetail',
  Endpoint.CHANGE_PASSWORD: '/Authentication/ChangePassword',
  Endpoint.TRANSACTION_PAYROLL_MANAGE_INIT: '/Payroll/Init',
  Endpoint.TRANSACTION_PAYROLL_MANAGE_CONFIRM: '/Payroll/Confirm',
  Endpoint.TRANSACTION_PAYROLL_MANAGE_COMMIT: '/Payroll/Commit',
  Endpoint.TRANSACTION_MANAGE_INIT: '/ManageTransaction/Init',
  Endpoint.TRANSACTION_MANAGE_CONFIRM: '/ManageTransaction/Confirm',
  Endpoint.TRANSACTION_SAVING_MANAGE_INIT: '/SavingOnline/InitTransaction',
  Endpoint.TRANSACTION_SAVING_MANAGE_CONFIRM:
      '/SavingOnline/ConfirmTransaction',
  Endpoint.TRANSACTION_SAVING_MANAGE_COMMIT: '/SavingOnline/CommitTransaction',
  Endpoint.TRANSACTION_PAYROLL_MANAGE_GET_BEN_LIST:
      '/Payroll/GetSalaryFileDetails',
  Endpoint.GET_CITY_LIST: '/Category/GetCityList',
  Endpoint.GET_BRANCH_LIST: '/Category/GetBranchList',
  Endpoint.RESEND_VERIFY_OTP: '/Authentication/ResendOTPFinancialService',
  Endpoint.GET_LIST_DEBIT_ACCOUNT: '/MadeFund/GetListDebitAccount',
  Endpoint.GET_BEN_ACCOUNT_DETAIL: '/MadeFund/GetBenAccountDetail',
  Endpoint.TRANSFER_INIT: '/MadeFund/Init',
  Endpoint.TRANSFER_CONFIRM: '/MadeFund/Confirm',
  Endpoint.GET_BEN_BANKS: '/Category/GetBenBanks',
  Endpoint.GET_BEN_LIST: '/MadeFund/GetBenList',
  Endpoint.GET_BANNER_AD: '/Category/GetBannerAdv',
  Endpoint.GET_ROLLOVER_TERM_SAVING_ONLINE:
      '/SavingOnline/GetRolloverTermSavingOnlineOfSMECustomer',
  Endpoint.GET_LIST_ACCOUNT_SETTING_NOTIFICATION:
      '/Notification/GetListDebitAccountNotification',
  Endpoint.POST_REGISTER_ACCOUNT_NOTIFICATIONS:
      '/Notification/RegisterAccountNofications',
  Endpoint.POST_DEREREGISTER_ACCOUNT_NOTIFICATIONS:
      '/Notification/DeregisterAccountNofications',
  Endpoint.GET_LIST_HISTORY_BALANCE_ALERT: '/getListHistoryBalanceAlert',
  Endpoint.GET_LIST_PAYMENT_PENDING_ALERT: '/getListTransferAlert',
  Endpoint.POST_HAS_READ_NOTIFICATIONS: '/hasReadNotification',
  Endpoint.GET_SAVING_DEPOSITS_PRODCUT:
      '/SavingOnline/GetListProductOpenOnlineSavingByCif',
  Endpoint.OPEN_SAVING_VERIFY: '/SavingOnline/Verify',
  Endpoint.GET_CARD_LIST: '/Card/GetCardList',
  Endpoint.GET_CARD_CONTRACT_LIST: '/Card/GetListCardContract',
  Endpoint.GET_CARD_HISTORY: '/Card/GetTransactionHistoryContractCard',
  Endpoint.GET_CARD_STATEMENT: '/Card/GetContractCardStatement',
  Endpoint.GET_CARD_STATEMENT_MONTH: '/Card/GetCardStmtMonth',
  Endpoint.GET_CARD_CONTRACT_INFO: '/Card/GetContractInfo',
  Endpoint.GET_CARD_INFO: '/Card/GetCardInfo',
  Endpoint.GET_LOAN_LIST: '/LoanContract/GetLoanContractList',
  Endpoint.GET_LOAN_DETAIL: '/LoanContract/GetLoanContractDetail',
  Endpoint.GET_LOAN_STATEMENT: '/LoanContract/GetLoanTranactionStatement',
  Endpoint.EXPORT_LOAN_DUE_DATE: '/LoanContract/ExportDueLoanStatement',
  Endpoint.GET_TAX_ONLINE: '/TaxRegisterOnline/GetCustomerDetailByTax',
  Endpoint.GET_TAX_ONLINE_LIST: '/TaxRegisterOnline/GetTaxOnlineRegisterList',
  Endpoint.MANAGE_TAX_ONLINE_INIT: '/TaxRegisterOnline/InitTransaction',
  Endpoint.MANAGE_TAX_ONLINE_CONFIRM: '/TaxRegisterOnline/ConfirmTransaction',
  Endpoint.MANAGE_TAX_ONLINE_COMMIT: '/TaxRegisterOnline/CommitTransaction',
  Endpoint.GET_LC: '/TradeFinanceReport/GetCollectionAndLCTransactionStatement',
  Endpoint.GET_GAURANTEE:
      '/TradeFinanceReport/GetGuaranteeTransactionStatement',
  Endpoint.GET_NEGOTING:
      '/TradeFinanceReport/GetNegotiatingTransactionStatement',
  Endpoint.GET_LC_CONTRACT_LIST: '/TradeFinanceReport/GetDRContractList',
  Endpoint.GET_LIST_NOTIFICATION_PROMOTE:
      '/Notification/GetListAdsNotification',
  Endpoint.GET_TRANSFER_RATE: '/MadeFund/GetRate',
  Endpoint.TRANSACTION_FX_MANAGE_INIT: '/ManageFxTransaction/Init',
  Endpoint.TRANSACTION_FX_MANAGE_CONFIRM: '/ManageFxTransaction/Confirm',
  Endpoint.TRANSACTION_FX_MANAGE_COMMIT: '/ManageFxTransaction/CommitTransaction',
  Endpoint.GET_BILL_SERVICE: '/BillPayment/GetService',
  Endpoint.GET_BILL_PROVIDER: '/BillPayment/GetProvider',
  Endpoint.GET_BILL_INFO: '/BillPayment/GetBillInformation',
  Endpoint.GET_BILL_SAVED: '/BillPayment/GetListSavedBill',
  Endpoint.BILL_INIT: '/BillPayment/Init',
  Endpoint.BILL_CONFIRM: '/BillPayment/Confirm',
  Endpoint.BILL_VERIFY: '/BillPayment/Verify',
  Endpoint.GET_BILL_DEBIT_ACCOUNT: '/BillPayment/GetListDebitAccount',
  Endpoint.GET_BILL_WAITING_APPROVAL: '/ManageBillTransaction/GetListTransferWaitingForApproval',
  Endpoint.INIT_BILL_MANAGE: '/ManageBillTransaction/Init',
  Endpoint.CONFIRM_BILL_MANAGE: '/ManageBillTransaction/Confirm',
  Endpoint.COMMIT_BILL_MANAGE: '/ManageBillTransaction/CommitTransaction',
};

extension EndpointExtension on Endpoint {
  String get value {
    return _data[this] ?? '';
  }
}
